; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.10 on Sun Dec 06 2020 22:17:00 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
; M116 P0

